apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: grocery-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: grocery-storage
  resources:
    requests:
      storage: 10Gi
